services:
  - type: web
    name: wati-work-bot
    env: python3.11
    plan: free
    autoDeploy: true
    cache: pip

    buildCommand: |
      apt-get update && apt-get install -y xvfb
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m playwright install chromium

    startCommand: xvfb-run -a python3 main.py

    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.playwright-browsers
      - key: PORT
        value: ${PORT}
